//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IbizcsWMS.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Label
    {
        public string LabelId { get; set; }
        public string Screen { get; set; }
        public string en_US { get; set; }
        public string zh_CN { get; set; }
        public short isOnPlaceHolder { get; set; }
    }
}
