//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TTAK_BLZRV2.Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValidateUserE
    {
        public int Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Company { get; set; }
        public string Language { get; set; }
        public string UserIp { get; set; }
        public string UserAgent { get; set; }
        public string Tk { get; set; }
        public string VerifyCode { get; set; }
    }
}
